swagger: '2.0'
info:
    title: 'Calculo de Seguros'
    version: 1.0.1
host: 0.0.0.0
schemes:
    - http
paths:
    /calcular-seguro:
        post:
            operationId: route1
            consumes:
                - application/json
            produces:
                - application/json
            parameters:
                -
                    name: body
                    in: body
                    required: true
                    schema:
                        $ref: '#/definitions/TtCalcSeguroRow'
            responses:
                '200':
                    description: 'Output type'
                    schema:
                        $ref: '#/definitions/CalcSeguroResponse'
definitions:
    TtCalcSeguroRow:
        type: object
        properties:
            MontoEquipo:
                format: double
                type: number
            CodigoAseguradora:
                format: int32
                type: integer
            CodigoClaseSeguro:
                format: int32
                type: integer
            CodigoTipoSeguro:
                format: int32
                type: integer
            CodigoCobertura:
                format: int32
                type: integer
            MonedaMontoEquipo:
                format: int32
                type: integer
            NumeroContrato:
                format: int32
                type: integer
            CotizacionEstimada:
                format: int32
                type: integer
            EmpresaDadora:
                format: int32
                type: integer
    CalcSeguroResponse:
        type: object
        properties:
            result:
                type: boolean
            errores:
                type: array
                items:
                    type: string
            opSegCalc:
                format: double
                type: number
